import { Navbar } from "@/components/Navbar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black relative pb-10 min-w-[300px]`}
      >
        <Navbar />
        <div className="w-full flex flex-col items-center gap-2 p-2 sm:p-8">
          <div className="grid md:grid-cols-2 grid-cols-1 grid-auto-rows-max gap-8 w-full max-w-[800px] p-8 text-white relative">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
